// import {message, user as us, test} from './library.js';
import * as dsk from './library.js';
console.log (message);
console.log (dsk.message);
// user("shubham");
// console.log (user ('shubham'));
console.log (dsk.user ('shubham'));
console.log (us ('shubham'));
let a = new test ();
let b = new dsk.test ();
